### ISSUE TITLE
JW Player Demo is broken

### ISSUE THREAD

**Issue by DoomTay** [Dador/JavascriptSubtitlesOctopus#10]
https://dador.github.io/JavascriptSubtitlesOctopus/jwplayer.html

It seems that a file the demo relies on has disappeared. Thankfully, [the file in question is well-preserved](https://web.archive.org/web/20170704193118js_/https://content.jwplatform.com/libraries/L7fM8L0h.js)

**Comment by Dador** [comment]
Thank you for reporting!

I've fixed the issue.
