### ISSUE TITLE
Option to change cache size

### ISSUE THREAD

**Issue by Dador** [Dador/JavascriptSubtitlesOctopus#12]
Add new option to change cache size.

For example right now we're using default cache size in libass (128MB + 64MB, so 192MB). Maybe it's worth to use lower default values for cache (if there is no big performance loss).

### Related links:
[ass_set_cache_limits](https://github.com/libass/libass/blob/master/libass/ass_render_api.c#L177)
[default cache size](https://github.com/libass/libass/blob/ad6510b9c78f5c79f7492b608912dc5281e15e47/libass/ass_render.h#L45)
[Relevant discussion in libass](https://github.com/libass/libass/issues/248#issuecomment-258826282)

**Comment by nickfujita** [comment]
While investigating support for use in a Google Chromecast Receiver application, I think that this issue might be applicable. When running the library in conjunction with video playback, the application quickly comes to a halt, and soon after crashes the device. Looking more into the issue, I was not able to capture a memory heap snapshot while on device because the device gets locked up before the snapshot is completed. However, when running in a desktop chrome browser, I am seeing an average heap snapshot of 140MB with it's majority allocation seemingly placed on the buffer.

![image](https://user-images.githubusercontent.com/6342442/34598219-b8d4d600-f22e-11e7-9fa3-31bc1619e6a6.png)

While not sure if this is potentially a use case for the changes to cache size, and making it configurable, but thought it might be worth mentioning. If the cache size could be made configurable on initialization, it might be worth investigating, as I believe it's ideal to keep total memory usage on a Chromecast device well below 150MB total.

**Comment by nickfujita** [comment]
I also tested this using only asm.js, and the results appear to be roughly the same. Would reducing the default cache size, also result in allowing us to configure a mix cache buffer size? If so, how might this affect rendering performance?

**Comment by Dador** [comment]
Reducing cache limit via [ass_set_cache_limits](https://github.com/libass/libass/blob/73284b676b12b47e17af2ef1b430527299e10c17/libass/ass.h#L478) ([source](https://github.com/libass/libass/blob/master/libass/ass_render_api.c#L181)) should result in lower memory usage.
You could try it by adding call like `ass_set_cache_limits(ass_renderer, 0, 64);` in [build/subtitles-octopus/subtitles-octopus-worker.c:41](https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/build/subtitles-octopus/subtitles-octopus-worker.c#L41)
(this example will leave cached glyphs limit as default and will set cache limit to 64MB overall)

You can experiment with cache size (and maybe add pull request with setting for it 😉).

> If so, how might this affect rendering performance?

I'm not sure, maybe it could affect complex karaoke performance or something like this. But I think performance would be same for ordinary substitles.

**Comment by nickfujita** [comment]
I am trying to run the library locally to make these updates, but run into the following error upon initial running on the repo as is:

![image](https://user-images.githubusercontent.com/6342442/35380883-daaab752-01fd-11e8-831f-555d546abb1b.png)

I installed emscripten and it's dependencies, also ran `source ./emsdk_env.sh` in the terminal I was working in before navigating to this repo's folder. Is this expected?

**Comment by Dador** [comment]
Try to update submodules.
You can do it using command:
```
git submodule update --init --recursive
```

**Comment by nickfujita** [comment]
Ran the commend to update submodules, but had no affect as I just did a fresh clone with:
`git clone --recursive -j8 git@github.com:Dador/JavascriptSubtitlesOctopus.git`

Ran `make` again, and still same message.

**Comment by Dador** [comment]
Does files from patches exists? If not, you should look for the reasons of it, because they are indeed in git repo.

**Comment by nickfujita** [comment]
I've confirmed that the patch files do exist, but it looks like the error is occurring when running the `fribidi-fixclang.patch` file. It somehow seems that while running this patch file it is not able to properly locate `lib/common.h`?

I ran this same procedure on another computer to make sure it was not something wrong with my setup, and got the same results. Are you not seeing the same thing on your end when doing a fresh copy of the repo running `git clone --recursive -j8 git@github.com:Dador/JavascriptSubtitlesOctopus.git`, `cd JavascriptSubtitleOctopus`, `make`?

**Comment by TFSThiagoBR98** [comment]
@nickfujita I think you forgot to install LLVM and clang

**Comment by nickfujita** [comment]
@TFSThiagoBR98 Thanks for the tip, I check to make sure I have LLVM and clang installed
```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
```

And updated to the latest version of Emscripten, `emscripten-1.37.36`.

However I am still back to getting the same error during patching:
```
make
cd build/fribidi && \
	git reset --hard && \
	patch -p1 < ../0001-Fix-Fribidi-Build.patch && \
	patch -p1 < ../fribidi-fixclang.patch && \
	NOCONFIGURE=1 ./autogen.sh
HEAD is now at 0cecb9e Version 2018.02.1
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/Makefile.am b/Makefile.am
|index 4767d69..3dba0d8 100644
|--- a/Makefile.am
|+++ b/Makefile.am
--------------------------
File to patch: 
```

After pressing return to skip, it just errors out in the same way:

```
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 18
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/gen.tab/Makefile.am b/gen.tab/Makefile.am
|index d178fc9..a8d4dc5 100644
|--- a/gen.tab/Makefile.am
|+++ b/gen.tab/Makefile.am
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
make: *** [build/fribidi/configure] Error 1
```

**Comment by TFSThiagoBR98** [comment]
> HEAD is now at 0cecb9e Version 2018.02.1

@nickfujita Did you checkout submodules? This is not Fribidi Git Commit Hash.
* If Yes, check if a .git file exist in fribidi directory.

**Comment by nickfujita** [comment]
@TFSThiagoBR98 I cloned down with:
`git clone --recursive -j8 git@github.com:Dador/JavascriptSubtitlesOctopus.git`

There is a `.git` file in the `bribidi` directory, it's contents are:
```
gitdir: ../../.git/modules/build/fribidi
```

This top level git directory also exists at that path, has several subdirectories files:
![image](https://user-images.githubusercontent.com/6342442/38348862-56e32ec2-38df-11e8-9e72-21f8da2392dd.png)

With the contents of the `HEAD` file being:
`0efbaa9052320a951823a6e776b30a580e3a2b4e`

**Comment by nickfujita** [comment]
Not sure where to go from here. Would really like to help to contribute to this repo, but the patches appear to not be working correctly. :(
