### ISSUE TITLE
flash player

### ISSUE THREAD

**Issue by anoosi** [Dador/JavascriptSubtitlesOctopus#16]
hello..
i tested in videojs and jwplayer,
when i use rtmp video,, the subtitle doesn't show..
![untitled](https://user-images.githubusercontent.com/14188374/32227561-cd3a4f2c-be5c-11e7-9539-41aca406991e.png)

i tried to change querySelector('video') to object, and no error in console
but subtitle just didn't show..

thanks ..

**Comment by Dador** [comment]
Because flash player doesn't have HTML5 video element thus we don't receive events like `playing`, `pause`, time updates and so on via standard way.

To resolve this issue, you have to add callbacks for these events via your player API and proxy these events to subtitles renderer.

**Comment by Dador** [comment]
Closing as it depends on Flash player implementation.
