### ISSUE TITLE
Assertion Error: MS Edge

### ISSUE THREAD

**Issue by nickfujita** [Dador/JavascriptSubtitlesOctopus#18]
When running on MS Edge the worker throws the error shown below. It appears that this only happens when trying to pull a subtitle file from an external source. When referencing a local file, as in the demo it seems to work properly. I tried passing the external url to the demo page, and it appears to be working just fine.

```
Assertion failed: track->n_events = track->max_events, at: ass.c,126,ass_alloc_event at Error
   at jsStackTrace (<domain>/subtitles-octopus-worker.js:1:25757)
   at stackTrace (<domain>/subtitles-octopus-worker.js:1:25929)
   at ___assert_fail (<domain>/subtitles-octopus-worker.js:1:142510)
   at Module[onRuntimeInitialized] (<domain>/subtitles-octopus-worker.js:1:6698)
   at doRun (<domain>/subtitles-octopus-worker.js:1:164158)
   at Anonymous function (<domain>/subtitles-octopus-worker.js:1:164392)
```

The error appears to be pointing to the following line in libass:
https://github.com/libass/libass/blob/master/libass/ass.c#L126

Any thoughts on why this assertion might be triggered?

**Comment by Dador** [comment]
What do you mean by external URL?
If it's URL on different domain, then it should support CORS (i.e. explicitly allow access to it from your domain). That's necessary because without CORS you can't access content of file on different domain.

**Comment by nickfujita** [comment]
Yes, I meant on a different domain. I don't think this is a CORS issue, and I am seeing that the library is working on all other browsers besides Edge, I don't see any errors coming up relating to CORS, and I even tried downloading the contents of the ASS file and then sending it in as content instead of just the URL.  I was running this on a Win10 VM and it seemed pretty resource constrained, so maybe it has to do with the worker not having enough resources? The portion of code that I linked above appears to reference some allocation for an event that is being made in C code. Have you come across this worker failure before?

**Comment by Dador** [comment]
Did you managed to resolve this issue?

**Comment by nickfujita** [comment]
The VM that I was using for MS was very resource constrained. Once I updated to testing on a better VM and on physical devices, the issue did not reoccur.
