### ISSUE TITLE
Font Map

### ISSUE THREAD

**Issue by Teranode** [Dador/JavascriptSubtitlesOctopus#2]
It would be great if there was a way to use a font map [in a css file] instead of individual fonts only like libjass or at lease be able to use a folder of fonts?

**Comment by Dador** [comment]
Exactly CSS map wouldn't make much sense because CSS isn't used.

But I think we can take array of fonts URLs with names (just like in CSS map), then parse source script in order to determine list of used fonts and finally preload only necessary fonts.

So that would look like that:
```javascript
var fonts = [
    {name: 'Arial', url: '/fonts/Arial.ttf'},
    {name: 'Tahoma', url: '/fonts/Tahoma.ttf'},
    {name: 'Roboto', url: '/fonts/Roboto.ttf'},
    // and so on...
];
```

Is that what you wanted?

**Comment by Teranode** [comment]
its more of that i have hundreds of already parsed fonts so scanning through the css for the font face family name and then using that would be nice

**Comment by Dador** [comment]
That how it looks like: https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/example/fonts_map.html#L21

**Comment by Teranode** [comment]
Hmm thats good enough, then final question would be. can I use a file to put all the fonts in?

E.G. https://external.animezero.tv/plugins/mediaplayer/assets/players/videojs/fonts.js

**Comment by Teranode** [comment]
@Dador

**Comment by Teranode** [comment]
Also what if fonts have Hyphens or Apostrophes in their name? cause some of them arent getting selected

**Comment by Yay295** [comment]
The @ isn't part of the name. It specifies that that font should be displayed vertically.

**Comment by Teranode** [comment]
@yay295 -> while that may be the case im not up for checking multiple sub files and adding @ to the list of font names.
