### ISSUE TITLE
Use browser system fonts

### ISSUE THREAD

**Issue by nickfujita** [Dador/JavascriptSubtitlesOctopus#24]
Instead of adding font files to be loaded into the library, would it be possible to take advantage of the system fonts that are already present within the browser?

**Comment by Dador** [comment]
In short: no, it's not possible.

JavaScript (and WebAssembly) doesn't have access to files on computer of user and for rendeding using libass it's necessary to have access to content of font files.
You will ask "but I can use system fonts in CSS!". Yes, you can show text using specified font. But browser only allows you to access the rendered result. Browser options for text size and positioning are very limited and exact result of this render may differ a lot depending on OS, browser or hardware.

Basically these limitations are the reason why it's almost impossible to correctly render subtitles in browser-only implementation of ass format (see known issues in [Arnavion/libjass](https://github.com/Arnavion/libjass)).

So you can use system fonts for redering ass subtitles but it's not suitable if your goal is to render them exactly like libass does. Text styles, spacing, positioning, etc will look different from libass. Sometimes it's not important (especially in case of simple subtitles) but it can be very important in other cases (complex styles which relies on features that's hard to implement in the browser).

**Comment by nickfujita** [comment]
Thanks for the quick and thorough response as always :)

**Comment by XCanG** [comment]
A little question, does library detect font name?
E.g. font name and font file `BILLO__.TTF`, I provide directly url to windows fonts in webserver and for JSO options write `/fonts/BILLO__.TTF`, but does it recognize, what font name is `BillboardOutline`? Because that's how it provided in ASS styles section.

**Comment by TFSThiagoBR98** [comment]
Yes, you have two ways to load fonts:

* Using `fonts: []` array, all fonts are download and saved in virtual fs and fontconfig loads the required fonts.
* Using `availableFonts: {}` map, the library parser subtitle file and download only the required fonts to virtual fs.

For [example](https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/example/fonts_map.html):

**Comment by qgustavor** [comment]
> JavaScript (and WebAssembly) doesn't have access to files on computer of user and for rendeding using libass it's necessary to have access to content of font files.

It's going to change: https://web.dev/local-fonts/
