### ISSUE TITLE
[Question] Font Rendering

### ISSUE THREAD

**Issue by Teranode** [Dador/JavascriptSubtitlesOctopus#3]
Is it normal that the subtitles takes several seconds to load after the video starts?
im checking the dev console and the fonts are preloaded the subs are preloaded but when the video starts it takes quite a while to render the subtitles after it starts

**Comment by Teranode** [comment]
May i also ask why its using specific commits of libass, freetype, fribidi?

**Comment by Dador** [comment]
> Is it normal that the subtitles takes several seconds to load after the video starts?
im checking the dev console and the fonts are preloaded the subs are preloaded but when the video starts it takes quite a while to render the subtitles after it starts
That's depends how many fonts you've preloaded. But with reasonable amout of fonts that shouldn't take so long (several seconds) to render subtitles after video starts. Even more, as you may see in example https://dador.github.io/JavascriptSubtitlesOctopus/videojs.html subtitles rendered before video even started.

So, do you experience same problem in [example](https://dador.github.io/JavascriptSubtitlesOctopus/videojs.html)? If so, then what browser do you use?

> May i also ask why its using specific commits of libass, freetype, fribidi?
There is no special meaning in them. I'm planning to update them to last version but that can make some troubles (like breaking patches) so I'm not done this yet.

**Comment by Teranode** [comment]
> There is no special meaning in them. I'm planning to update them to last version but that can make some troubles (like breaking patches) so I wasn't done this yet.

Ive been using the latest version of libass, i haven't touched the other commits due to most of them breaking when i do (mostly fribidi)

> So, do you experience same problem in example? If so, then what browser do you use?

Im fine with the loading (did some testing with different players, JWPlayer and VideoJs seems to perform better in rendering the subtitles with minimal impact to time, flowplayer however suffers from this dillema.)

A question i had want t ask is with the implementation of the new way the fonts can be listed by name ( the question i had asked way back and then you put it in an update), Would it be possible to put those list of font names in a file that way everyone doesn't have to be inline?

**Comment by Dador** [comment]
> A question i had want t ask is with the implementation of the new way the fonts can be listed by name ( the question i had asked way back and then you put it in an update), Would it be possible to put those list of font names in a file that way everyone doesn't have to be inline?

You can load fonts map via AJAX and then pass it to Octopus.

For example with jQuery:
```
 $.getJSON("http://link-to-json-with-fonts-map/", function (fonts) {
        window.SubtitlesOctopusOnLoad = function () {
            var options = {
                video: video,
                subUrl: '/example/test.ass',
                availableFonts: fonts, // All available fonts (font name should be lower case). It will load only fonts really used in sub.
                //onReady: onReadyFunction,
                //debug: true,
                workerUrl: '/js/subtitles-octopus-worker.js'
            };
            window.octopusInstance = new SubtitlesOctopus(options); // You can experiment in console
        };
        if (SubtitlesOctopus) {
            SubtitlesOctopusOnLoad();
        }
    });
```

**Comment by Teranode** [comment]
thanks

**Comment by Teranode** [comment]
this is general question, but is to possible to load this in chromecast?

**Comment by Dador** [comment]
I'm not sure about styled subtitles (don't know nuances how chromcast works). But looks like you can add simple subtitles (vtt):
https://developers.google.com/cast/docs/chrome_sender_advanced
https://github.com/benjipott/video.js-chromecast

**Comment by Yay295** [comment]
Yes: https://support.google.com/chromecast/answer/3228332?hl=en

**Comment by Dador** [comment]
I'm closing this issue as question seems to be resolved.
