### ISSUE TITLE
[Question] Unloading / updating subtitles

### ISSUE THREAD

**Issue by XCanG** [Dador/JavascriptSubtitlesOctopus#32]
What is the properly way to unload / reload subtitle? My player playing more, than one file and some of it don't have subtitles and some of them using another one.

Currently I just removing html element for clearing from old subs, but I'm not sure if sub stop processing in library or not.

```
document.querySelectorAll(".libassjs-canvas-parent").forEach((el) => el.remove());
```

**Comment by TFSThiagoBR98** [comment]
By 19ec946, You can use `setTrackByUrl(url)` and `setTrack(content)` functions to set tracks without restart JSO

**Comment by TFSThiagoBR98** [comment]
For an example, see: https://dador.github.io/JavascriptSubtitlesOctopus/mediaelement.html

**Comment by XCanG** [comment]
Oh, that was useful info.
