### ISSUE TITLE
Unable to build with Emscripten 1.38.19

### ISSUE THREAD

**Issue by matthewn4444** [Dador/JavascriptSubtitlesOctopus#34]
Hello,

I am on Ubuntu 16.04 and tried to build this project. I am using 1.38.19 emscripten and clang versions when choosing which to activate that should be the "latest" after running **source ./emsdk_env.sh**.  After downloading emscripten from scratch and this project without any modifications I get these issues.

My error gets me when trying to build harfbuzz (freetype is fine): 

```
 configure: error: could not determine /media/sf_repositories/emsdk/emscripten/1.38.19/emar interface
 ERROR:root:Configure step failed with non-zero return code: 1.  Command line: ./configure CFLAGS=-O3 --prefix=/media/path_to_files/JavascriptSubtitlesOctopus/dist/libraries --host=x86-none-linux --build=x86_64 --disable-static --enable-shared --disable-dependency-tracking --without-cairo --without-fontconfig --without-icu --with-freetype --without-glib at /media/path_to_files/JavascriptSubtitlesOctopus/lib/harfbuzz
 Makefile:83: recipe for target 'dist/libraries/lib/libharfbuzz.so' failed
 make: *** [dist/libraries/lib/libharfbuzz.so] Error 1
```

I get the same error when trying build with docker and other versions of emscripten below this version.

My steps are basically

1. emsdk install <sdk version>
2. emsdk activate <sdk version>
3. source ./emsdk_env.sh
4. cd <change to project folder>
5. make

and then the original instructions for docker.

Weirdly I was able to build a while ago but it doesnt work now.

I also tried to build with version 1.37.1 which built fine (except failed to install fontconfig and I had to manually create a fontconfig.pc to build libass). 

With that version my output is not the same as the files in ""/dist"". My subtitles-octopus-worker.js output has an error when running a simple call

```
 let options = { 
         video: document.querySelect("#video"),
          subUrl: "url/to/sub.ass",
          fonts: [],
          workerUrl: "sub/subtitles-octopus-worker.js"
};            
 this.octopusInstance = new SubtitlesOctopus(options);
 ```

Console looks like this when it loads 

![stacktrace](https://farm5.staticflickr.com/4864/32110889418_0da39dc2ba_b.jpg)

```
trying binaryen method: native-wasm
Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
```

Which these errors may be related to emscripten doing something wierd.

This has been awhile since I compiled the project (I actually need to get ass_process_data exposed) but for some reason cannot build anymore. I also attached the subtitles-octopus-worker.js file, if you can figure out what I am doing wrong that would be great.

[subtitles-octopus-worker.log, rename the "log" into "js"](https://github.com/Dador/JavascriptSubtitlesOctopus/files/2603191/subtitles-octopus-worker.log)

**Comment by TFSThiagoBR98** [comment]
> configure: error: could not determine /media/sf_repositories/emsdk/emscripten/1.38.19/emar interface
Probably there is a problem in your Emscripten, try to reinstall it.

For avoid problems:
* Run `make clean` to clean artifacts and temp files before build. WARNING: THIS WILL DELETE ALL FILES NOT ADDED TO GIT INDEX

See if it will work, if not, send me the config.log files inside each library folder

**Comment by matthewn4444** [comment]
I have tried  multiple times cloning the original emsdk and following the same steps and I get this. What version do you use? Do you just grab the emsdk and activate the latest version?

Yes I always run make clean when changing the emsdk version or starting from scratch to do this but I get that error all the time. 
harfbuzz fails but freetype was built fine.

I attached the only library with a log, harfbuzz (that was failing to build). However if i force expat or another library to build first I get the same error, presumably the same log.

[config.log](https://github.com/Dador/JavascriptSubtitlesOctopus/files/2604949/config.log)
 log.

**Comment by matthewn4444** [comment]
Ok so I figured it out. I will close this. The issue was because I put the files and tried building through the shared folders in virtualbox. It builds fine with all the files in Ubuntu.
