### ISSUE TITLE
destory -> destroy

### ISSUE THREAD

**Issue by martingronlund** [Dador/JavascriptSubtitlesOctopus#36]
Is the following intentional?

https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/src/subtitles-octopus.js#L472

https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/src/post-worker.js#L739

If it is I don't think it should be, so this is an issue in any case.

**Comment by Dador** [comment]
No, it's just a typo and not intentional. Thank you for noticing.
P.S. Of course it's easy to fix so feel free to do it. I can't do it right now though (I don't have building environment nearby).

**Comment by TFSThiagoBR98** [comment]
I'll fix it
