### ISSUE TITLE
Document subtitle switching

### ISSUE THREAD

**Issue by cobarx** [Dador/JavascriptSubtitlesOctopus#38]
PR #31 added support for switching subtitles without re-initializing the engine. We should get the API for this documented in the README. @YePpHa Would you mind putting together a quick PR for this?

**Comment by cobarx** [comment]
@YePpHa Quick reminder to document this if you get a chance.

**Comment by YePpHa** [comment]
Ahh yeah. Sorry about that. I forgot all about this. I will try to get it done soon.

**Comment by cobarx** [comment]
Thanks @YePpHa, these enhancements to the docs are great!
