### ISSUE TITLE
Not a circle

### ISSUE THREAD

**Issue by PiRomant** [Dador/JavascriptSubtitlesOctopus#39]
{\shad0\bord4\fs185\b1\fscx135\fscy135\pos(329,116)\c&H4423EB&\3c&H64CED9&}.
Looks ![image](https://user-images.githubusercontent.com/29551044/51087183-25455980-1782-11e9-84f8-cf417fcbadc3.png)
Should be ![image](https://user-images.githubusercontent.com/29551044/51087191-545bcb00-1782-11e9-9f82-f4beb10854c7.png)

**Comment by Yay295** [comment]
There should be more to that line. Just an override block without any text or a path wouldn't display anything at all.

**Comment by PiRomant** [comment]
[test.zip](https://github.com/Dador/JavascriptSubtitlesOctopus/files/2753542/test.zip)

**Comment by Yay295** [comment]
Here's a trimmed down version of that file:

```
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 800
PlayResY: 448
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: test,Trebuchet MS,185,&H004423EB,&H00EFDC97,&H0064CED9,&H209F3B22,-1,-1,0,0,135,135,0,0,1,4,0,8,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:01:00.00,test,,0,0,0,,.
```

Perhaps it's a font issue? All that's happening is they're making a period really big, so if it's loading the wrong font, it might not be the correct shape.

**Comment by PiRomant** [comment]
You right.
