### ISSUE TITLE
Is there SRT support?

### ISSUE THREAD

**Issue by phly95** [Dador/JavascriptSubtitlesOctopus#42]
If I use this for a web player, does it accept SRT subtitles or only SSA/ASS subtitles?

**Comment by Dador** [comment]
It supports only SSA/ASS subtitles.
You can convert SRT subtitles to ASS using ffmpeg: https://trac.ffmpeg.org/wiki/HowToConvertSubtitleToASS
You can also take a look on projects like [srt-to-ass](https://github.com/OwenRay/srt-to-ass)
