### ISSUE TITLE
Could you please consider giving your project a license?

### ISSUE THREAD

**Issue by elarkham** [Dador/JavascriptSubtitlesOctopus#5]
Just found your project and I'm blown away by it, I had never considered rendering .ass files by just directly compiling libass into javascript. Really surprised how well the whole thing works and I'm considering using it in one of my hobby projects, possibly even forking it in the future. Before I do this though I would feel a lot more comfortable if you attached a license to it, hope this isn't to much of a bother.

**Comment by Dador** [comment]
Hi.

Maybe you have some suggestions for the exact licence? It should be compatible with libass and it's dependencies.

**Comment by elarkham** [comment]
After doing a quick review of all of their licenses:
[expat:](https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/build/expat/COPYING) BSD-Style
[fontconfig:](https://cgit.freedesktop.org/fontconfig/tree/COPYING) BSD-Style
[freetype:](https://www.freetype.org/license.html) BSD-Style (or GPL since they let you use one or the other)
[fribidi:](https://github.com/behdad/fribidi/blob/master/COPYING) LGPL (Different from GPL in that as long as you use it as a library and don't modify it, your project does not have to be LGPL/GPL)
[libass:](https://github.com/libass/libass/blob/7c30feaa6906c5f392f6a1496462504b09fd8df0/COPYING) BSD-Style
[zlib:](http://www.zlib.net/zlib_license.html) BSD-Style

Since all of these licenses (except fribidi if you modify it) are permissive, you have a lot of leeway here. I'd recommend something simple like BSD or MIT, something more complicated like GPL are where things get a bit hairy so I'd avoid stuff like that.

**Comment by elarkham** [comment]
I'm not really an expert on this stuff btw, so take that as you will.

**Comment by Dador** [comment]
Sorry for long wait. I selected MIT.

Here: https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/LICENSE
