### ISSUE TITLE
webpack - wasm streaming compile failed

### ISSUE THREAD

**Issue by jiseopX** [Dador/JavascriptSubtitlesOctopus#50]
Hi i wanna try the library but i got an error.
I am getting error as follows.
```
subtitles-octopus-worker.js:235 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
I am using webpack for bundling and did not edit any configuration

**Comment by Dudecake** [comment]
Your issue is the result of your devserver not serving the `subtitles-octopus.wasm` file with the correct `application/wasm` mime type. Depending on the devserver you use, the configuration to set the correct `application/wasm` mime type will differ.

**Comment by jiseopX** [comment]
Can you tell me how to set configuration file for webpack to get it work?
