### ISSUE TITLE
Since version 2.1 it is no longer possible to use woff font file

### ISSUE THREAD

**Issue by LukePulverenti** [Dador/JavascriptSubtitlesOctopus#55]
I don't know if you were ever intending on supporting this, but with earlier versions we were able to use a .woff font file.

For us this is important because we have a large 6 MB font file with support for a large range of encodings. Having the ability to use a .woff font resulted in nearly a 4 MB savings compared to the ttf version.

**Comment by TFSThiagoBR98** [comment]
@LukePulverenti Version 3.0.1 adds support for woff2 files

**Comment by LukePulverenti** [comment]
That's great, I'll try this out. Thanks !
