### ISSUE TITLE
Add support for changing one specific line? like text, start end, end time

### ISSUE THREAD

**Issue by 1c7** [Dador/JavascriptSubtitlesOctopus#59]
## Use case
I am building a Subtitle Editing Software using Electron.js + Vue.js (kinda like a replacement for Aegisub)

Users can update Text, Start Time, End Time. (one line at a time)

For now, JavascriptSubtitlesOctopus 3.0.2 only support replace the entire thing

![image](https://user-images.githubusercontent.com/1804755/72444167-82874700-37ea-11ea-9952-979a35900878.png)

Would it be possible to support edit only one line in the future?
Thanks

**Comment by Dador** [comment]
In case you're looking how to expose more APIs from libass:
- Here is ASS_Track from libass: https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/src/subtitles-octopus-worker.c#L13
- And info about ASS_Track: https://github.com/libass/libass/blob/master/libass/ass_types.h#L176 (I guess you can use ASS_Track->events array to modify events) (info about ASS_Event and ASS_Style located in the same file)
- If you add function to file https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/src/subtitles-octopus-worker.c you can mark it as exported in file https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/Makefile#L297 and after that access it in JavaScript https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/src/pre-worker.js#L51

This is just some tips in case you want to play around with it.

Lately mostly @TFSThiagoBR98 maintains this library (thank you! 🙂), so I think he's more suitable person to ask about new features.

**Comment by 1c7** [comment]
@Dador  Thank you for the very detailed answer!

@TFSThiagoBR98 Would you mind taking a look at this Github issue?

I have very limited C, C++, Makefile, Web assembly knowledge, 
so it would probably take me a lot of time to understand how this library works and change it. and than send a Pull Requests

**Comment by TFSThiagoBR98** [comment]
@1c7 hello, I'm studying a way to implement this, but due to lack of time, I'm just going to work on this weekend

**Comment by 1c7** [comment]
THANK YOU!

**Comment by 1c7** [comment]
Thanks again!
