### ISSUE TITLE
Program terminated with exit(4)

### ISSUE THREAD

**Issue by 1c7** [Dador/JavascriptSubtitlesOctopus#60]
# Environment
in `Electron.js 6.1.5` Desktop app,   
I was trying to use `JavascriptSubtitlesOctopus`

# Error
![image](https://user-images.githubusercontent.com/1804755/72494604-61147280-385f-11ea-831c-147004cecaa3.png)

# Zoom in picture
![image](https://user-images.githubusercontent.com/1804755/72494673-97ea8880-385f-11ea-98b9-0fbc2a9172b2.png)

# Reproducible code
https://github.com/1c7/Electron-JavascriptSubtitlesOctopus
```
git clone https://github.com/1c7/Electron-JavascriptSubtitlesOctopus.git
cd Electron-JavascriptSubtitlesOctopus/
npm install
npm run dev
```

## Thank you!
@Dador 
@TFSThiagoBR98

**Comment by TFSThiagoBR98** [comment]
It is very simple, the track was not found, because the sub_url parameter is absolute and not relative.
change this subUrl: './1.ass' to subUrl: './js/1.ass'

**Comment by 1c7** [comment]
Thank you for the reply!
I would try that solution and come back with result, Thanks!

**Comment by 1c7** [comment]
not working. would you mind to help me again? @TFSThiagoBR98

**Comment by 1c7** [comment]
it's working now
![image](https://user-images.githubusercontent.com/1804755/72727122-1ed39400-3bc5-11ea-938f-2dd6665a2cbb.png)
The rest is font issue. I can handle it myself.

**Comment by 1c7** [comment]
let me close this issue for now.

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/72727208-50e4f600-3bc5-11ea-88f6-b74e7d1e5243.png)
This work too

**Comment by 1c7** [comment]
# font issue is fixed!
![image](https://user-images.githubusercontent.com/1804755/72727536-19c31480-3bc6-11ea-87a3-b0e88c2f9d39.png)

**Comment by 1c7** [comment]
Thanks, all problem solved :)
