### ISSUE TITLE
fontselect problem with my ffmpeg build

### ISSUE THREAD

**Issue by anoosi** [Dador/JavascriptSubtitlesOctopus#67]
hi
for some time now I have been trying to build ffmpeg with libass and harfbuzz,
I have a problem with the fonts!
the problem is when the font does not exist or the font it self is not supported by libass Library, the program does not take another default font as in SubtitlesOctopus
so I'm just wondering if it comes to how to build options in libass or fontconfig library because your SubtitlesOctopus is done very well for this detail
I apologize for opening the issue here but I couldn't find a better place to ask about this since you did it well
thanks.

**Comment by TFSThiagoBR98** [comment]
https://github.com/Dador/JavascriptSubtitlesOctopus/blob/bacdf324881700c29c7103500d6a4e685d1fb674/src/SubtitleOctopus.cpp#L185

Here is set the fallback font file
