### ISSUE TITLE
Create a full width box

### ISSUE THREAD

**Issue by ajimix** [Dador/JavascriptSubtitlesOctopus#68]
I'm trying to create subtitles like the following screenshot:

<img width="808" alt="CleanShot 2020-04-24 at 22 08 38@2x" src="https://user-images.githubusercontent.com/30565/80221657-30bb4c00-8678-11ea-8daa-943f6a9a5af4.png">

Where there is a background box going from side to side.

I couldn't find any ass option to do a full-width background so I've managed to do the box by drawing it manually, but the problem is that the box is disconnected from the text, so I never know the required height of the box and some multiline subtitles end up outside of the box.

What is the solution for this?

**Comment by ajimix** [comment]
I've already figured out how to do it sorry. This issue can be deleted

**Comment by francisashley** [comment]
How did you do it?

**Comment by ajimix** [comment]
> How did you do it?

Using the shadow ass modifier `{\xshad400}`

**Comment by francisashley** [comment]
Thank you sir! I got it working but with `{\xbord400}`.
