### ISSUE TITLE
Latest version is throwing errors on web

### ISSUE THREAD

**Issue by nickfujita** [Dador/JavascriptSubtitlesOctopus#70]
While trying to upgrade from v2.1.1, I ran into a few issues.

- v4.0.0 does not appear to have the dist files updated with the latest changes to memory limiting
- The project development appears to have been deviated to 3 separate repos (Dador, JustAMan, jellyfin), where the jelyifin fork looking to be the latest. @jellyfin or @JustAMan Any chance we can look to merge your wonderful updates back to the original repo?
- A simple web example is no longer working on the latest version. I've created a very simple test example webpage to showcase the player, as the original example in the readme no longer exists. However it seems that a simple web example is no longer working. [More details here.](https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/17) Anyone else seeing the same thing?

**Comment by nickfujita** [comment]
Created a PR with the same simple web example against this original repo, but still does not appear to be working properly.

https://github.com/Dador/JavascriptSubtitlesOctopus/pull/71

**Comment by nickfujita** [comment]
@TFSThiagoBR98 Noticed that the original examples folder was removed in https://github.com/Dador/JavascriptSubtitlesOctopus/commit/37d81c3e19d777c545d090e49a05dd0a303c6849. Was this ever migrated somewhere else?

**Comment by JustAMan** [comment]
@nickfujita I was planning on making upstreaming PRs, but then real life happened... I still hope to do them, though. Meanwhile anyone is free to do that if they want to :)
